name: laml
channels:
  - defaults
dependencies:
  - ipykernel
  - pip
  - python=3.9
  - pip:
    - black
    - ipywidgets
    - lightning==1.8.3.post1
    - mlflow==2.0.1
    - pytorch-lightning==1.8.3.post1
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchdata==0.5.0
    - torchmetrics==0.11.0
    - torchtext==0.14.0
    - torchvision==0.14.0
    - azureml-fsspec
